version: '3'
services:
  nginx:
    build:
      context: ./docker
      dockerfile: nginx.docker
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - php-fpm
  mysql:
    image: mysql:5.7
    volumes:
      - ./var/docker/mysql:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_USER=app"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_DATABASE=app"
    ports:
      - "33061:3306"
  php-cli:
    build:
      context: ./docker
      dockerfile: php-cli.docker
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    tty: true
  php-fpm:
    build:
      context: ./docker
      dockerfile: php-fpm.docker
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql

  storage-nginx:
    build:
      context: ./docker/storage
      dockerfile: nginx.docker
    volumes:
      - ./storage:/var/www/storage
    ports:
      - "8083:80"

  imap-mail:
    image: tvial/docker-mailserver:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    container_name: ${CONTAINER_NAME}
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - maillogs:/var/log/mail
      - ./config/common/imap:/tmp/docker-mailserver/
    env_file:
      - .env
      - env-mailserver
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always

volumes:
  mysql:
  maildata:
    driver: local
  mailstate:
    driver: local
  maillogs:
    driver: local
